### ISSUE TITLE
CFE Upgrades

### ISSUE THREAD

**Issue by AlastairHolmes** [chainflip-io/chainflip-backend#3064]
### Description

This issue is for tracking the SC and CFE changes we decided on.

https://www.notion.so/chainflip/Network-Health-CFE-Upgrade-Handling-557e99d1a36a4285bfbd4989c65a2dcc

- CFE waits for correct runtime version (while old version is running)
- Runtime needs to be aware of compatible CFE versions (Min / Max range)
- Failsafe in the governance pallet - refuse runtime upgrade unless enough cfes are up-to-date.
- Storage item ‘NextVersion’ so CFE can check if it’s ready for an upgrade.
- Current version and pending/ready version on SC reported by CFE
- Stick with (beautified) script.

**Comment by kylezs** [comment]
This is done now.
